# Generated by Django 3.0.7 on 2021-03-21 09:47

from django.db import migrations


def add_order_items_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')

    for order_item in OrderItem.objects.all():
        order_item.price = order_item.product.price * order_item.quantity
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_order_items_price)
    ]
