# Generated by Django 3.0.7 on 2021-03-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0002_auto_20210321_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unproc', 'Unprocessed'), ('Proc', 'Processed')], default='Unproc', max_length=6, verbose_name='Статус заказа'),
        ),
    ]
