# Generated by Django 3.0.7 on 2021-03-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unproc', 'Необработанный'), ('Proc', 'Обработанный')], db_index=True, default='Unproc', max_length=6, verbose_name='Статус заказа'),
        ),
    ]
