# Generated by Django 3.0.7 on 2021-03-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0006_auto_20210327_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Cash', 'Наличными'), ('Electro', 'По карте')], db_index=True, default='Cash', max_length=7, verbose_name='Метод оплаты'),
        ),
    ]
