# Generated by Django 3.0.7 on 2021-03-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0007_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Cash', 'Наличными'), ('Electro', 'По карте'), ('Undef', 'Не выбрано')], db_index=True, default='Undef', max_length=7, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unproc', 'Необработанный'), ('Proc', 'Доставляется'), ('Done', 'Доставлен')], db_index=True, default='Unproc', max_length=6, verbose_name='Статус заказа'),
        ),
    ]
