# Generated by Django 3.0.7 on 2021-03-08 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('product', models.ManyToManyField(related_name='order_items', to='foodcartapp.Product', verbose_name='Продукт в заказе')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='foodcartapp.OrderItem', verbose_name='Товары'),
            preserve_default=False,
        ),
    ]
